"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG").lower() == "true"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOST").split(",")


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_reportbroD.apps.ReportbrodConfig",
    "apps.base",
    "apps.users",
    "apps.biblioteca",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": os.environ.get("DATABASE_NAME"),
    #     "USER": os.environ.get("DATABASE_USER"),
    #     "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
    #     "HOST": os.environ.get("POSTGRES_HOST"),
    #     "PORT": int(os.environ.get("POSTGRES_PORT")),
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "es-ar"  #'en-us'

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Mensajes personalizados de autenticación
LOGIN_ERROR_MESSAGE = "Credenciales incorrectas"

# STATIC_URL = '/static/'
# STATICFILES_DIRS = (BASE_DIR, 'static')
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    'apps.biblioteca.auth.ArchivoAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

JAZZMIN_SETTINGS = {
    "custom_index": "admin/index.html",
    "welcome_sign": "Bienvenido",
    "site_title": "Biblioteca",
    "site_header": "Biblioteca",
    "site_brand": "Biblioteca",
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_logo_dark": "img/logo.png",
    "site_logo_classes": "",
    "topmenu_links": [
        {
            "name": "Plantillas Reportes",
            "url": "/reportbroD",
            "permissions": [
                "reportbroD.view_reportrequest",
                "reportbroD.delete_reportrequest",
                "reportbroD.change_reportrequest",
                "reportbroD.add_reportrequest",
                "reportbroD.view_reportdefinition",
                "reportbroD.delete_reportdefinition",
                "reportbroD.change_reportdefinition",
                "reportbroD.add_reportdefinition",
            ],
        },
    ],
    "custom_links": {
        "biblioteca": [{
            "name": "Asistente de Rcomendaciones", 
            "url": "/asistente/paso1", 
            "icon": "fas fa-robot",
        }
        ,{
            "name": "Mis Datos", 
            "url": "/mis-datos", 
            "icon": "fas fa-book",
        }
        ]
    },
    "show_ui_builder": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "auth.Permission": "fas fa-key",
        "biblioteca.Archivo": "fas fa-archive",
        "biblioteca.ArchivoEntrada": "fas fa-door-open",
        "biblioteca.Asistencia": "fas fa-user-check",
        "biblioteca.AsistenteRecomendaciones": "fas fa-robot",
        "biblioteca.ComentarioLibro": "fas fa-comment",
        "biblioteca.Concurso": "fas fa-trophy",
        "biblioteca.ConfiguracionBiblio": "fas fa-cog",
        "biblioteca.Inventario": "fas fa-boxes",
        "biblioteca.Lecturade_libro": "fas fa-book-reader",
        "biblioteca.Libro": "fas fa-book",
        "biblioteca.LibroDigital": "fas fa-file-pdf",
        "biblioteca.LibrosDelMes": "fas fa-star",
        "biblioteca.MaterialAudiovisual": "fas fa-film",
        "biblioteca.Mobiliario": "fas fa-chair",
        "biblioteca.MuestrasMes": "fas fa-images",
        "biblioteca.PrestamoLibro": "fas fa-hand-holding",
        "biblioteca.PrestamoRevista": "fas fa-hand-holding",
        "biblioteca.Revista": "fas fa-newspaper",
        "biblioteca.Suscriptor": "fas fa-id-card",
        "biblioteca.Trabajador": "fas fa-user-tie",
        "biblioteca.UsuariosEventuales": "fas fa-user-clock",
    },
    "order_with_respect_to": [
        "auth",
        "biblioteca.Archivo",
        "biblioteca.ArchivoEntrada",
        "biblioteca.Asistencia",
        "biblioteca.AsistenteRecomendaciones",
        "biblioteca.ComentarioLibro",
        "biblioteca.Concurso",
        "biblioteca.ConfiguracionBiblio",
        "biblioteca.Inventario",
        "biblioteca.Lecturade_libro",
        "biblioteca.Libro",
        "biblioteca.LibroDigital",
        "biblioteca.LibrosDelMes",
        "biblioteca.MaterialAudiovisual",
        "biblioteca.Mobiliario",
        "biblioteca.MuestrasMes",
        "biblioteca.PrestamoLibro",
        "biblioteca.PrestamoRevista",
        "biblioteca.Revista",
        "biblioteca.Suscriptor",
        "biblioteca.Trabajador",
        "biblioteca.UsuariosEventuales",
        "users",
    ],
}
JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False,
    "custom_css": "css/admin_custom.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
    "related_modal_active": False,
    "message_success_color": "#28a745",
    "message_warning_color": "#ffc107",
    "message_error_color": "#dc3545",
    "message_info_color": "#17a2b8",
}

DJANGO_SUPERUSER_USERNAME = os.environ.get("DJANGO_SUPERUSER_USERNAME")
DJANGO_SUPERUSER_PASSWORD = os.environ.get("DJANGO_SUPERUSER_PASSWORD")
DJANGO_SUPERUSER_EMAIL = os.environ.get("DJANGO_SUPERUSER_EMAIL")
DJANGO_SUPERUSER_FIRST_NAME = os.environ.get("DJANGO_SUPERUSER_FIRST_NAME")
DJANGO_SUPERUSER_LAST_NAME = os.environ.get("DJANGO_SUPERUSER_LAST_NAME")

# JAZZMIN_UI_TWEAKS = {
#     "theme": "darkly",
#     "dark_mode_theme": "darkly",
# }
X_FRAME_OPTIONS = 'SAMEORIGIN'