# Generated by Django 4.2.7 on 2024-07-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_cierre", models.DateField(verbose_name="Fecha de Cierre")),
                ("nombre", models.CharField(max_length=256, verbose_name="Nombre")),
                (
                    "descrpcion",
                    models.CharField(max_length=256, verbose_name="Descripción"),
                ),
                (
                    "categorias",
                    models.CharField(max_length=256, verbose_name="Categoria"),
                ),
                (
                    "modalidad",
                    models.CharField(max_length=256, verbose_name="Modalidad"),
                ),
            ],
            options={
                "verbose_name": "Concurso",
                "verbose_name_plural": "Concursos",
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=256, verbose_name="Título")),
                (
                    "editorial",
                    models.CharField(max_length=256, verbose_name="Editorial"),
                ),
                ("autor", models.CharField(max_length=256, verbose_name="Autor")),
                (
                    "fecha_publicacion",
                    models.DateField(verbose_name="Fecha de Publicación"),
                ),
                ("edicion", models.CharField(max_length=256, verbose_name="Edición")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Bueno", "Bueno"),
                            ("Regular", "Regular"),
                            ("Malo", "Malo"),
                        ],
                        max_length=256,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=256, verbose_name="Ubicación"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=256, verbose_name="Descripción"),
                ),
                ("genero", models.CharField(max_length=256, verbose_name="Género")),
                (
                    "fecha_adquisicion",
                    models.DateField(verbose_name="Fecha de Adquisición"),
                ),
                (
                    "numero_copias",
                    models.IntegerField(verbose_name="Número de Copias Disponibles"),
                ),
                (
                    "numero_serie",
                    models.CharField(max_length=256, verbose_name="Número de Serie"),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
            },
        ),
        migrations.CreateModel(
            name="MaterialAudiovisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=256, verbose_name="Título")),
                (
                    "creador",
                    models.CharField(max_length=256, verbose_name="Creador o Autor"),
                ),
                (
                    "fecha_produccion",
                    models.DateField(verbose_name="Fecha de Producción"),
                ),
                (
                    "productora",
                    models.CharField(max_length=256, verbose_name="Productora"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Bueno", "Bueno"),
                            ("Regular", "Regular"),
                            ("Malo", "Malo"),
                        ],
                        max_length=256,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=256, verbose_name="Ubicación"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=256, verbose_name="Descripción"),
                ),
                (
                    "genero",
                    models.CharField(max_length=256, verbose_name="Género o Categoria"),
                ),
                ("formato", models.CharField(max_length=256, verbose_name="Formato")),
                (
                    "fecha_adquisicion",
                    models.DateField(verbose_name="Fecha de Adquisición"),
                ),
                (
                    "numero_copias",
                    models.IntegerField(verbose_name="Número de Copias Disponibles"),
                ),
                (
                    "numero_serie",
                    models.CharField(max_length=256, verbose_name="Número de Serie"),
                ),
            ],
            options={
                "verbose_name": "Material Audivisual",
                "verbose_name_plural": "Materiales Audiovisuales",
            },
        ),
        migrations.CreateModel(
            name="Mobiliario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_tipoMueble",
                    models.CharField(
                        max_length=256, verbose_name="Nombre o Tipo de Mueble"
                    ),
                ),
                ("numero_serie", models.IntegerField(verbose_name="Número de Serie")),
                (
                    "ubicacion",
                    models.CharField(max_length=256, verbose_name="Ubicación"),
                ),
                (
                    "dimenciones",
                    models.CharField(max_length=256, verbose_name="Dimenciones"),
                ),
                (
                    "costo_adqisicion",
                    models.IntegerField(verbose_name="Costo de Adquisición"),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Bueno", "Bueno"),
                            ("Regular", "Regular"),
                            ("Malo", "Malo"),
                        ],
                        max_length=256,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobiliario",
                "verbose_name_plural": "Mobiliario",
            },
        ),
        migrations.CreateModel(
            name="MuestrasMes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_muestra",
                    models.CharField(max_length=256, verbose_name="Título"),
                ),
                (
                    "tipo_muestra",
                    models.CharField(max_length=256, verbose_name="Tipo de Muestra"),
                ),
                ("autor", models.CharField(max_length=256, verbose_name="Autor")),
                (
                    "responsable",
                    models.CharField(max_length=256, verbose_name="Responsable"),
                ),
                (
                    "descrpcion",
                    models.CharField(max_length=256, verbose_name="Descripción"),
                ),
                (
                    "genero",
                    models.CharField(max_length=256, verbose_name="Género o Categoria"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "horario_inicio",
                    models.DateTimeField(verbose_name="Horario de inicio"),
                ),
                (
                    "horario_Cierre",
                    models.DateTimeField(verbose_name="Horario de cierre"),
                ),
                (
                    "edad_minima",
                    models.IntegerField(verbose_name="Edad Minima Recomendada"),
                ),
                (
                    "edad_maxima",
                    models.IntegerField(verbose_name="Edad Máxima Recomendada"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=256, verbose_name="Dirección"),
                ),
            ],
            options={
                "verbose_name": "Muestra del Mes",
                "verbose_name_plural": "Muestras del Mes",
            },
        ),
        migrations.CreateModel(
            name="Revista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=256, verbose_name="Nombre de la Revista"
                    ),
                ),
                (
                    "perioricidad",
                    models.CharField(max_length=256, verbose_name="Perioricidad"),
                ),
                (
                    "numero",
                    models.CharField(max_length=256, verbose_name="Número de Volumen"),
                ),
                (
                    "fecha_publicacion",
                    models.DateField(verbose_name="Fecha de Publicación"),
                ),
                (
                    "editorial",
                    models.CharField(max_length=256, verbose_name="Editorial"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Bueno", "Bueno"),
                            ("Regular", "Regular"),
                            ("Malo", "Malo"),
                        ],
                        max_length=256,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=256, verbose_name="Ubicación"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=256, verbose_name="Descripción"),
                ),
                (
                    "fecha_adquisicion",
                    models.DateField(verbose_name="Fecha de Adquisición"),
                ),
                (
                    "numero_copias",
                    models.IntegerField(verbose_name="Número de Copias Disponibles"),
                ),
                (
                    "numero_serie",
                    models.CharField(max_length=256, verbose_name="Número de Serie"),
                ),
            ],
            options={
                "verbose_name": "Revista",
                "verbose_name_plural": "Revista",
            },
        ),
        migrations.CreateModel(
            name="Suscriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256, verbose_name="Nombre")),
                ("edad", models.IntegerField(verbose_name="Edad")),
                ("sexo", models.CharField(max_length=256, verbose_name="Sexo")),
                ("Telefono", models.CharField(max_length=256, verbose_name="Teléfono")),
                ("ci", models.IntegerField(verbose_name="CI")),
                (
                    "centro_trabajo",
                    models.CharField(
                        max_length=256, verbose_name="Centro de Trbajo o Estudio "
                    ),
                ),
                (
                    "ocupacion",
                    models.CharField(max_length=256, verbose_name="Ocupación"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=256, verbose_name="Dirección"),
                ),
                ("sindicato", models.BooleanField(default=False)),
                (
                    "nivel_escolar",
                    models.CharField(
                        max_length=256, verbose_name="Nivel de Escolaridad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscriptor",
                "verbose_name_plural": "Suscriptores",
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256, verbose_name="Nombre")),
                ("edad", models.IntegerField(verbose_name="Edad")),
                ("sexo", models.CharField(max_length=256, verbose_name="Sexo")),
                ("Telefono", models.CharField(max_length=256, verbose_name="Teléfono")),
                ("ci", models.IntegerField(verbose_name="CI")),
                ("expediente", models.IntegerField(verbose_name="Expediente")),
                (
                    "direccion",
                    models.CharField(max_length=256, verbose_name="Dirección"),
                ),
                ("sindicato", models.BooleanField(default=False)),
                (
                    "nivel_escolar",
                    models.CharField(
                        max_length=256, verbose_name="Nivel de Escolaridad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(verbose_name="Fecha de Prestamo")),
                ("fecha_entrga", models.DateField(verbose_name="Fecha de Entrega")),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "suscriptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.suscriptor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestamo",
                "verbose_name_plural": "Pretamos",
            },
        ),
        migrations.CreateModel(
            name="LibrosDelMes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lobro del mes",
                "verbose_name_plural": "Libros del Mes",
            },
        ),
        migrations.CreateModel(
            name="Lecturade_libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "suscriptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.suscriptor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesctura de libro",
                "verbose_name_plural": "Lescturas de libros",
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("libros", models.ManyToManyField(to="biblioteca.libro")),
                (
                    "materiales_audiovisuales",
                    models.ManyToManyField(to="biblioteca.materialaudiovisual"),
                ),
                ("mobiliarios", models.ManyToManyField(to="biblioteca.mobiliario")),
                ("revistas", models.ManyToManyField(to="biblioteca.revista")),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe de Assitecias",
                "verbose_name_plural": "Informes de Asistencias",
            },
        ),
    ]
