# Generated by Django 4.2.7 on 2025-04-17 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='libro_infantil',
        ),
        migrations.AddField(
            model_name='libro',
            name='edad_maxima',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad Máxima Recomendada'),
        ),
        migrations.AddField(
            model_name='libro',
            name='edad_minima',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad Mínima Recomendada'),
        ),
        migrations.AddField(
            model_name='libro',
            name='ilustraciones',
            field=models.BooleanField(default=False, verbose_name='Tiene Ilustraciones'),
        ),
        migrations.AddField(
            model_name='libro',
            name='tipo_libro',
            field=models.CharField(choices=[('normal', 'Libro Normal'), ('infantil', 'Libro Infantil')], default='normal', max_length=10, verbose_name='Tipo de Libro'),
        ),
        migrations.DeleteModel(
            name='LibroInfantil',
        ),
    ]
