# Generated by Django 4.2.7 on 2025-04-17 22:39

import apps.biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_prestamo_libro_infantil_libro_edad_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, validators=[apps.biblioteca.models.no_futuro], verbose_name='Fecha'),
        ),
    ]
