# Generated by Django 4.2.7 on 2025-04-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_comentariolibro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='revista',
        ),
    ]
