# Generated by Django 4.2.7 on 2024-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0005_alter_lecturade_libro_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialaudiovisual",
            name="numero_serie",
            field=models.CharField(max_length=256, verbose_name="Número de Serie"),
        ),
        migrations.AlterField(
            model_name="muestrasmes",
            name="horario_Cierre",
            field=models.TimeField(verbose_name="Horario de cierre"),
        ),
        migrations.AlterField(
            model_name="muestrasmes",
            name="horario_inicio",
            field=models.TimeField(verbose_name="Horario de inicio"),
        ),
        migrations.AlterField(
            model_name="revista",
            name="numero",
            field=models.CharField(max_length=256, verbose_name="Número de Volumen"),
        ),
    ]
