# Generated by Django 4.2.7 on 2025-04-23 20:44

import apps.biblioteca.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_remove_prestamo_revista'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Apellido')),
                ('ci', models.IntegerField(validators=[apps.biblioteca.models.length_validation_11, django.core.validators.RegexValidator('^[0-9]{11}$'), apps.biblioteca.models.not_empty_validation], verbose_name='CI')),
                ('horaentrada', models.DateTimeField(verbose_name='Hora de Entrada')),
                ('horasalida', models.DateTimeField(verbose_name='Hora de Salida')),
            ],
            options={
                'verbose_name': 'Archivo de Entrada y Salida',
                'verbose_name_plural': 'Archivos de Entradas y Salidas',
            },
        ),
        migrations.CreateModel(
            name='PrestamoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(validators=[apps.biblioteca.models.no_futuro], verbose_name='Fecha de Préstamo')),
                ('fecha_entrga', models.DateField(verbose_name='Fecha de Entrega')),
                ('devolucion', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.suscriptor')),
            ],
            options={
                'verbose_name': 'Préstamo de Libro',
                'verbose_name_plural': 'Préstamos de Libros',
            },
        ),
        migrations.CreateModel(
            name='PrestamoRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(validators=[apps.biblioteca.models.no_futuro], verbose_name='Fecha de Préstamo')),
                ('fecha_entrga', models.DateField(verbose_name='Fecha de Entrega')),
                ('devolucion', models.BooleanField(default=False)),
                ('revista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.revista')),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.suscriptor')),
            ],
            options={
                'verbose_name': 'Préstamo de Revistas',
                'verbose_name_plural': 'Préstamos de Revistas',
            },
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
