# Generated by Django 4.2.7 on 2025-05-01 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_archivoentrada_prestamolibro_prestamorevista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Título')),
                ('autor', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Autor')),
                ('archivo_pdf', models.FileField(help_text='Sube el archivo PDF del libro', upload_to='libros_digitales/', verbose_name='Archivo PDF')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('descripcion', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ,.!¡¿?]+$')], verbose_name='Descripción')),
                ('genero', models.CharField(blank=True, choices=[('Ficcion', 'Ficcion'), ('No ficción', 'No ficción'), ('Ciencia ficción', 'Ciencia ficción'), ('Fantasía', 'Fantasía'), ('Aventura', 'Aventura'), ('Policíaca', 'Policíaca'), ('Romántico', 'Romántico')], max_length=256, null=True, verbose_name='Género')),
                ('edad_minima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad Mínima Recomendada')),
                ('edad_maxima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad Máxima Recomendada')),
            ],
            options={
                'verbose_name': 'Libro Digital',
                'verbose_name_plural': 'Libros Digitales',
            },
        ),
    ]
