# Generated by Django 4.2.7 on 2024-09-16 02:31

import apps.biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0007_alter_prestamo_options_revista_numero1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="fecha",
            field=models.DateField(
                auto_now_add=True,
                validators=[apps.biblioteca.models.no_futuro],
                verbose_name="Fecha",
            ),
        ),
        migrations.AlterField(
            model_name="materialaudiovisual",
            name="formato",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MP4", "MP4"),
                    ("AVI", "AVI"),
                    ("MOV", "MOV"),
                    ("WMV", "WMV"),
                    ("FLV", "FLV"),
                    ("WebM", "WebM"),
                    ("MPEG", "MPEG"),
                    ("3GP", "3GP"),
                    ("AVCHD", "AVCHD"),
                ],
                max_length=256,
                null=True,
                verbose_name="Formato",
            ),
        ),
        migrations.AlterField(
            model_name="revista",
            name="perioricidad",
            field=models.CharField(
                choices=[
                    ("Semanal", "Semanal"),
                    ("Quincenal", "Quincenal"),
                    ("Mensual", "Mensual"),
                    ("Bimestral", "Bimestral"),
                    ("Trimestral", "Trimestral"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                    ("Irregular", "Irregular"),
                ],
                max_length=256,
                verbose_name="Perioricidad",
            ),
        ),
    ]
