# Generated by Django 4.2.7 on 2024-12-13 22:55

import apps.biblioteca.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("biblioteca", "0009_suscriptor_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuariosEventuales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        validators=[apps.biblioteca.models.no_pasado],
                        verbose_name="Fecha",
                    ),
                ),
                ("caduco", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario Eventual",
                "verbose_name_plural": "Usuarios Eventuales",
            },
        ),
    ]
