# Generated by Django 4.2.7 on 2024-12-13 23:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0010_usuarioseventuales"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="cantidad_prestamo",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad de prestamo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialaudiovisual",
            name="cantidad_prestamo",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad de prestamo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="revista",
            name="cantidad_prestamo",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad de prestamo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="libro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteca.libro",
            ),
        ),
    ]
