# Generated by Django 4.2.7 on 2024-12-13 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0011_libro_cantidad_prestamo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestamo",
            name="revista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="biblioteca.revista",
            ),
        ),
    ]
