# Generated by Django 4.2.7 on 2024-12-15 19:47

import apps.biblioteca.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_prestamo_revista'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Título')),
                ('editorial', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Editorial')),
                ('autor', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Autor')),
                ('fecha_publicacion', models.DateField(validators=[apps.biblioteca.models.no_futuro], verbose_name='Fecha de Publicación')),
                ('edicion', models.CharField(blank=True, max_length=256, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Edición')),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=256, verbose_name='Estado')),
                ('ubicacion', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Ubicación')),
                ('descripcion', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Descripción')),
                ('genero', models.CharField(blank=True, choices=[('Ficcion', 'Ficcion'), ('No ficción', 'No ficción'), ('Ciencia ficción', 'Ciencia ficción'), ('Fantasía', 'Fantasía'), ('Aventura', 'Aventura'), ('Policíaca', 'Policíaca'), ('Romántico', 'Romántico')], max_length=256, null=True, verbose_name='Género')),
                ('fecha_adquisicion', models.DateField(validators=[apps.biblioteca.models.no_futuro], verbose_name='Fecha de Adquisición')),
                ('numero_copias', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Copias Disponibles')),
                ('numero_serie', models.IntegerField(max_length=256, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Serie')),
                ('cantidad_prestamo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de prestamo')),
                ('ilustracioes', models.BooleanField(default=False)),
                ('edad_minima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad Minima Recomendada')),
                ('edad_maxima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edad Máxima Recomendada')),
            ],
            options={
                'verbose_name': 'Libro Infantil',
                'verbose_name_plural': 'LIbros Infantiles',
            },
        ),
        migrations.AddField(
            model_name='revista',
            name='Pais',
            field=models.CharField(default='Cuba', max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='País'),
            preserve_default=False,
        ),
    ]
