# Generated by Django 4.2.7 on 2024-12-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_libroinfantil_revista_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='factor_estancia',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroinfantil',
            name='factor_estancia',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
