# Generated by Django 4.2.7 on 2024-12-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_configuracionbiblio_libro_peso_libroinfantil_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='libro_infantil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libroinfantil'),
        ),
        migrations.AlterField(
            model_name='configuracionbiblio',
            name='peso_maximo',
            field=models.FloatField(default=0),
        ),
    ]
