# Generated by Django 4.2.7 on 2025-01-04 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0018_prestamo_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_paginas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Páginas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='materia',
            field=models.CharField(default=0, max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='pais',
            field=models.CharField(default=0, max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='resumen',
            field=models.CharField(default=0, max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Resumen del Contenido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroinfantil',
            name='cantidad_paginas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Páginas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroinfantil',
            name='materia',
            field=models.CharField(default=0, max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroinfantil',
            name='pais',
            field=models.CharField(default=0, max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroinfantil',
            name='resumen',
            field=models.CharField(default=0, max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')], verbose_name='Resumen del Contenido'),
            preserve_default=False,
        ),
    ]
