# Generated by Django 4.2.7 on 2025-04-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0020_alter_archivo_options_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuarioseventuales'),
        ),
    ]
