# Generated by Django 4.2.7 on 2025-04-15 23:18

import apps.biblioteca.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0021_alter_archivo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'Archivo Histórico', 'verbose_name_plural': 'Archivos Históricos'},
        ),
        migrations.RemoveField(
            model_name='usuarioseventuales',
            name='caduco',
        ),
        migrations.AddField(
            model_name='archivo',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarioseventuales',
            name='fecha',
            field=models.DateField(validators=[apps.biblioteca.models.no_pasado], verbose_name='Fecha de vencimiento'),
        ),
    ]
